### PR TITLE
Registry adress fix

### PR DESCRIPTION
**Pull request by fixator10**
Current version causes error on my end:

Traceback (most recent call last):
  File "gmaddown_console.py", line 34, in <module>
    aKey = OpenKey(aReg, r"SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion
\Uninstall\Steam App 4000")
FileNotFoundError: [WinError 2] Не удается найти указанный файл

### CODE REVIEW

**Comment by magnusjjj** [comment]
Hi!

Thank you _so_ much for the input! That registry key does not exist on my system, so can't accept the pull request verbatim, but I have an idéa how to fix it now. Will at first run time loop through a couple of registry key, test if files actually exist, and then write a best_gmad_guess.txt :). Patch'll be up in... well. When its done, but you'll be mentioned in it :).

**Comment by magnusjjj** [comment]
Can you

**Comment by magnusjjj** [comment]
Can you test if my changes work for you? :)

**Comment by fixator10** [comment]
Yep, thx.

**Pull request closed without merging**
